apiVersion: v1
kind: Pod
metadata:
  name: counter-pod
  labels:
    app: counter
spec:
  containers:
  - name: counter
    image: python:3.9-slim
    command: ["python", "-c"]
    args:
    - |
      import time
      import sys
      import os
      
      print(f"PID: {os.getpid()}")
      i = 0
      while True:
        print(f"Stateful Counter: {i}")
        sys.stdout.flush()
        i += 1
        time.sleep(1)
